name: "PREC | Link Assets from Description"

on:
  workflow_dispatch: {}
  schedule:
    - cron: "16 3 * * *"

jobs:
  scan-and-link:
    runs-on: ubuntu-latest
    env:
      JIRA_SITE: "https://cnhpd.atlassian.net"
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      ASSETS_WORKSPACE_ID: ${{ secrets.ASSETS_WORKSPACE_ID }}

      OBJECT_SCHEMA_ID: "3"   # PV Assets
      # BROAD JQL (we'll filter in code by issue type)
      JQL: >
        project = PREC AND statusCategory != Done
      # Regex for the issue type (case-insensitive). Adjust if needed.
      MISSION_RELEASE_TYPES: "(?i)^mission\\s*/\\s*release$"

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Debug – list first 20 PREC keys with type & status
        run: |
          python - <<'PY'
          import os, requests
          JIRA_SITE=os.environ["JIRA_SITE"].rstrip("/")
          AUTH=(os.environ["JIRA_EMAIL"], os.environ["JIRA_API_TOKEN"])
          H={"Accept":"application/json"}
          jql=os.environ["JQL"]
          url=f"{JIRA_SITE}/rest/api/3/search/jql"
          r=requests.get(url,headers=H,auth=AUTH,params={"jql":jql,"maxResults":20,"fields":"key,issuetype,status"})
          r.raise_for_status()
          data=r.json()
          issues=data.get("issues",[])
          print(f"Returned: {len(issues)}")
          for i in issues:
            key=i["key"]
            itype=i["fields"]["issuetype"]["name"]
            status=i["fields"]["status"]["name"]
            print(f"{key}  |  {itype}  |  {status}")
          PY

      - name: Query PREC and add asset web links (enhanced JQL + type filter)
        run: |
          python - <<'PY'
          import os, sys, json, time, re
          import requests

          JIRA_SITE           = os.environ["JIRA_SITE"].rstrip("/")
          JIRA_EMAIL          = os.environ["JIRA_EMAIL"]
          JIRA_API_TOKEN      = os.environ["JIRA_API_TOKEN"]
          ASSETS_WORKSPACE_ID = os.environ["ASSETS_WORKSPACE_ID"]
          OBJECT_SCHEMA_ID    = os.environ["OBJECT_SCHEMA_ID"]
          JQL                 = os.environ["JQL"]
          TYPE_REGEX          = os.environ.get("MISSION_RELEASE_TYPES", r"(?i)^mission\s*/\s*release$")

          AUTH = (JIRA_EMAIL, JIRA_API_TOKEN)
          H    = {"Accept":"application/json","Content-Type":"application/json"}
          type_pat = re.compile(TYPE_REGEX)

          def die(msg, r=None):
              if r is not None:
                  print(f"{msg} ({r.status_code}): {r.text}", file=sys.stderr)
              else:
                  print(msg, file=sys.stderr)
              sys.exit(1)

          # ---------- Enhanced JQL search with cursor pagination ----------
          def search_get(jql, next_token=None, fields=None, max_results=100):
              url = f"{JIRA_SITE}/rest/api/3/search/jql"
              params = {"jql": jql, "maxResults": max_results}
              if fields:
                  params["fields"] = ",".join(fields)
              if next_token:
                  params["nextPageToken"] = next_token
              return requests.get(url, headers=H, auth=AUTH, params=params)

          def search_post(jql, next_token=None, fields=None, max_results=100):
              url = f"{JIRA_SITE}/rest/api/3/search/jql"
              body = {"jql": jql, "maxResults": max_results}
              if fields:
                  body["fields"] = fields
              if next_token:
                  body["nextPageToken"] = next_token
              return requests.post(url, headers=H, auth=AUTH, json=body)

          def enhanced_search(jql, wanted_fields):
              next_token = None
              while True:
                  r = search_get(jql, next_token=next_token, fields=wanted_fields)
                  if r.status_code in (404,405,410):
                      r = search_post(jql, next_token=next_token, fields=wanted_fields)
                  if r.status_code != 200:
                      die("Jira enhanced search failed", r)
                  page = r.json()
                  for issue in page.get("issues", []):
                      yield issue
                  next_token = page.get("nextPageToken")
                  if not next_token:
                      break

          # ---------- Issue helpers ----------
          def get_issue_desc(key):
              url = f"{JIRA_SITE}/rest/api/3/issue/{key}?fields=description"
              r = requests.get(url, headers=H, auth=AUTH)
              if r.status_code != 200:
                  die(f"Failed to read description for {key}", r)
              return r.json().get("fields",{}).get("description") or ""

          def list_remote_links(key):
              url = f"{JIRA_SITE}/rest/api/3/issue/{key}/remotelink"
              r = requests.get(url, headers=H, auth=AUTH)
              if r.status_code != 200:
                  die(f"Failed to list remote links for {key}", r)
              links = r.json() if isinstance(r.json(), list) else []
              existing = set()
              for l in links:
                  obj = l.get("object",{})
                  title = obj.get("title") or ""
                  url   = obj.get("url") or ""
                  if title and url:
                      existing.add((title.strip(), url.strip()))
              return existing

          def create_remote_link(key, title, url_):
              url = f"{JIRA_SITE}/rest/api/3/issue/{key}/remotelink"
              r = requests.post(url, headers=H, auth=AUTH, json={"object":{"title": title, "url": url_}})
              if r.status_code not in (200,201):
                  die(f"Failed to create remote link for {key}", r)

          # ---------- Assets lookup (schema 3) ----------
          def aql_lookup(category, name):
              aql = (
                  f'objectSchemaId = {OBJECT_SCHEMA_ID} '
                  f'AND objectType = "{category}" '
                  f'AND (Name = "{name}" OR "Serial Number" = "{name}")'
              )
              url = f"{JIRA_SITE}/jsm/assets/workspace/{ASSETS_WORKSPACE_ID}/v1/object/aql"
              r = requests.post(url, headers=H, auth=AUTH, json={"qlQuery": aql, "page":1, "resultPerPage":2})
              if r.status_code != 200:
                  die("Assets AQL search failed", r)
              data = r.json() or {}
              objs = data.get("objectEntries") or []
              return objs[0] if objs else None

          def asset_url(object_id:int):
              return f"{JIRA_SITE}/jira/servicedesk/assets/objects/{object_id}"

          # ---------- Parse the bullet tree ----------
          bullet_re = re.compile(r"^(?:-|\*)\s+(?P<cat>.+?)\s*$")
          child_re  = re.compile(r"^\s{2,}(?:-|\*)\s+(?P<name>.+?)\s*$")

          def extract_pairs(desc_text):
              pairs = []
              current_cat = None
              text = desc_text if isinstance(desc_text, str) else ""
              for raw in (text or "").splitlines():
                  line = raw.rstrip()
                  m1 = bullet_re.match(line)
                  if m1:
                      current_cat = m1.group("cat").strip()
                      continue
                  m2 = child_re.match(line)
                  if m2 and current_cat:
                      nm = m2.group("name").strip()
                      if nm:
                          pairs.append((current_cat, nm))
              return pairs

          # ---------- Main ----------
          wanted_fields = ["summary","description","issuetype","project","status"]
          total_scanned = 0
          matched_types = set()

          for issue in enhanced_search(JQL, wanted_fields):
              key    = issue["key"]
              f      = issue.get("fields") or {}
              proj   = f.get("project", {}).get("key")
              itype  = (f.get("issuetype", {}) or {}).get("name","")
              status = (f.get("status", {}) or {}).get("name","")

              if proj != "PREC":
                  continue

              # only Mission/Release types
              if not type_pat.match(itype or ""):
                  continue

              # skip validated complete
              if status == "Validated (Complete)":
                  continue

              matched_types.add(itype)

              desc = f.get("description") or ""
              pairs = extract_pairs(desc if isinstance(desc, str) else get_issue_desc(key))
              if not pairs:
                  print(f"{key}: no asset tree detected; skipping")
                  continue

              existing = list_remote_links(key)
              for cat, nm in pairs:
                  obj = aql_lookup(cat, nm)
                  if not obj:
                      print(f"{key}: not found in Assets (schema 3) → {cat} / {nm}")
                      continue
                  oid = obj.get("id")
                  url_ = asset_url(oid)
                  title = f"{cat} - {nm}"

                  if (title, url_) in existing:
                      print(f"{key}: link already exists → {title}")
                      continue

                  create_remote_link(key, title, url_)
                  existing.add((title, url_))
                  print(f"{key}: linked {title}")

              total_scanned += 1
              time.sleep(0.2)

          print(f"Done. Issues scanned: {total_scanned}. Matched types seen: {sorted(matched_types)}")
          PY
